#version: '3'
services:
  basket:
    build: .
    image: basket_api
    container_name: basket_api
    working_dir: /work
    volumes:
      - ./work:/work
    ports:
      - "8888:8888"
    command: >
      jupyter-lab 
      --ip 0.0.0.0 
      --allow-root 
      --no-browser
      --NotebookApp.token='' 
      --NotebookApp.password=''
      -b localhost